### ISSUE TITLE
Lastvalues

### ISSUE THREAD

**Issue by csqzs** [Luoyonghong/Multivariate-Time-Series-Imputation-with-Generative-Adversarial-Networks#1]
您好，看了您的代码，我有一个疑问：代码中的Lastvalues和Subvalues 无论是在训练还是在测试中都没有用到？那您处理Lastvalues和Subvalues的用意是什么那？

**Comment by Luoyonghong** [comment]
您好，Lastvalues和Subvalues都是历史遗留，用于实验各个proposed methods的优劣。你可以不用管它。

**Comment by csqzs** [comment]
好的 ，感谢您的回复。
